/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f95ee09c-a6a5-45ec-ba10-98a5d208cd45 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool switch2;
  bool switch1;
  bool switch3;
  bool switch4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define buttonPin1 D0
#define buttonPin2 D1
#define buttonPin3 D2
#define buttonPin4 D3

void setup() {
  
  pinMode(buttonPin1, INPUT_PULLUP);
  pinMode(buttonPin2, INPUT_PULLUP);
  pinMode(buttonPin3, INPUT_PULLUP);
  pinMode(buttonPin4, INPUT_PULLUP);
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  int buttonState1 = digitalRead(buttonPin1);
  int buttonState2 = digitalRead(buttonPin2);
  int buttonState3 = digitalRead(buttonPin3);
  int buttonState4 = digitalRead(buttonPin4);
  
  if(buttonState1 == LOW){
    switch1 = !switch1;
    delay(100);
  }
  if(buttonState2 == LOW){
    switch2 = !switch2;
    delay(100);
  }
  if(buttonState3 == LOW){
    switch3 = !switch3;
    delay(100);
  }
  if(buttonState4 == LOW){
    switch4 = !switch4;
    delay(100);
  }
  
}

void onSwitch2Change() {
  // Do something
}

void onSwitch1Change() {
  // Do something
}

void onSwitch3Change() {
  // Do something
}

void onSwitch4Change() {
  // Do something
}
