/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f95ee09c-a6a5-45ec-ba10-98a5d208cd45 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool switch2;
  bool switch1;
  bool switch3;
  bool switch4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define relayPin1 13
#define relayPin2 12
#define relayPin3 14
#define relayPin4 27

void setup() {
  pinMode(relayPin1, OUTPUT);
  pinMode(relayPin2, OUTPUT);
  pinMode(relayPin3, OUTPUT);
  pinMode(relayPin4, OUTPUT);
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


void onSwitch1Change() {
  // Do something
  if (switch1 == 1) {
    digitalWrite(relayPin1, HIGH);
  }
  else {
    digitalWrite(relayPin1, LOW);
  }
}

void onSwitch2Change() {
  // Do something
  if (switch2 == 1) {
    digitalWrite(relayPin2, HIGH);
  }
  else {
    digitalWrite(relayPin2, LOW);
  }
}

void onSwitch3Change() {
  // Do something
  if (switch3 == 1) {
    digitalWrite(relayPin3, HIGH);
  }
  else {
    digitalWrite(relayPin3, LOW);
  }   
}

void onSwitch4Change() {
  // Do something
  if (switch4 == 1) {
    digitalWrite(relayPin4, HIGH);
  }
  else {
    digitalWrite(relayPin4, LOW);
  }   
}
