#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/5ad72f1b-f7a3-42fc-9c76-33bae6c59ea2

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool relay1;
  bool relay2;
  bool relay3;
  bool relay4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define relay1_pin 13
#define relay2_pin 12
#define relay3_pin 14
#define relay4_pin 27

void setup() {
  pinMode(relay1_pin, OUTPUT);
  pinMode(relay2_pin, OUTPUT);
  pinMode(relay3_pin, OUTPUT);
  pinMode(relay4_pin, OUTPUT);

  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here


}

void onRelay1Change() {
  Serial.println("On-Change Event Relay1");
  if (relay1 == 1) {
    digitalWrite(relay1_pin, HIGH);
  }
  else {
    digitalWrite(relay1_pin, LOW);
  }
}

void onRelay2Change() {
  Serial.println("On-Change Event Relay2");
  if (relay2 == 1) {
    digitalWrite(relay2_pin, HIGH);
  }
  else {
    digitalWrite(relay2_pin, LOW);
  }
}
void onRelay3Change() {
  Serial.println("On-Change Event Relay3");
  if (relay3 == 1) {
    digitalWrite(relay3_pin, HIGH);
  }
  else {
    digitalWrite(relay3_pin, LOW);
  }
}

void onRelay4Change() {
  Serial.println("On-Change Event Relay4");
  if (relay4 == 1) {
    digitalWrite(relay4_pin, HIGH);
  }
  else {
    digitalWrite(relay4_pin, LOW);
  }
}
